version: '2'
services:
  meet-backend:
    build: ../meet-backend/
    depends_on:
      - meet-db
    ports:
      - "8080:8080"
    networks:
      - meet-network
    command: ['npm', 'start']
  meet-admin-backend:
    build: ../meet-admin-backend/
    depends_on:
      - meet-db
    ports:
      - "8081:8081"
    networks:
      - meet-network
    command: ['npm', 'start']
  meet-db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - meet-network
    restart: always
    volumes:
      - meet-db-data:/var/lib/mongodb
networks:
  meet-network:
    driver: bridge

volumes:
  meet-db-data:
    driver: local
